<?php

namespace AppBundle\Repository;

/**
 * AttractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttractionRepository extends \Doctrine\ORM\EntityRepository
{


    public function getWhatYouWant()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.type != :type')
            ->setParameter('type', 'zzz');

        return $qb->getQuery()
            ->getResult();
    }


}
