<?php

namespace AppBundle\Repository;

/**
 * AttractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttractionRepository extends \Doctrine\ORM\EntityRepository
{
}
